name: Daily Resume Upload

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 AM UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  upload-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright with required dependencies
      run: npx playwright install chromium --with-deps

    - name: Upload Resume using xvfb
      env:
        NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" node upload.js