name: Daily Resume Upload

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC (adjust as needed)
  workflow_dispatch:     # Allow manual run from GitHub UI

jobs:
  upload-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Resume Upload Script
      env:
        NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: node upload.js